language: python
branches:
  only: 
    - master
python:
  - "3.6"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - git submodule init
  - git submodule update
  - ./scripts/get_static_validation.sh
# command to install dependencies
install: 
  - pip install pipenv
  - pipenv install --dev
  - nvm install 8
  - npm install
  - npm run prod
# command to run tests
script:
  - pipenv run py.test -c pytest_ci.ini tests/
  - pipenv run prospector  --profile-path=. --profile=.prospector.yml --path=src --ignore-patterns=static
  - pipenv run bandit -r src
  - npm run coverage
  - npm run lintjs
  - npm run lintscss
